if('serviceWorker'in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('service-worker.js')})}
function formatPrice(p){try{return new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(p)}catch{return'₱'+p.toFixed(2)}}
async function loadMenu(id){const el=document.getElementById(id);try{const res=await fetch('data/menu.json');const d=await res.json();el.innerHTML='';for(const s of d.sections){const c=document.createElement('div');c.className='card';c.innerHTML=`<h2>${s.title}</h2><p>${s.description||''}</p>`;const g=document.createElement('div');g.className='grid';for(const it of s.items){const div=document.createElement('div');div.className='menu-item';div.innerHTML=`<h4>${it.name}</h4><div class='price'>${formatPrice(it.price)}</div><div>${it.note||''}</div>`;g.appendChild(div)}c.appendChild(g);el.appendChild(c)}}catch(e){el.innerHTML='<div class="notice">Could not load menu.</div>'}}
async function loadEvents(id){const el=document.getElementById(id);try{const res=await fetch('data/events.json');const d=await res.json();el.innerHTML='';for(const ev of d.events){const c=document.createElement('div');c.className='card';const dt=new Date(ev.date);c.innerHTML=`<h3>${ev.title}</h3><p>${dt.toLocaleString()}</p><p>${ev.description||''}</p>`;el.appendChild(c)}}catch(e){el.innerHTML='<div class="notice">Could not load events.</div>'}}
function readStamps(){return parseInt(localStorage.getItem('vb_stamps')||'0',10)}function writeStamps(n){localStorage.setItem('vb_stamps',String(n));renderStamps()}
function renderStamps(){const n=readStamps();const c=document.getElementById('stamps');if(!c)return;c.innerHTML='';for(let i=1;i<=10;i++){const s=document.createElement('div');s.className='stamp'+(i<=n?' filled':'');s.textContent=i<=n?'✓':'';c.appendChild(s)}document.getElementById('stampCount').textContent=n;const r=document.getElementById('redeemBtn');if(r)r.disabled=n<10}
function addStampWithCode(){const code=prompt('Enter staff code to add a stamp:');if(code&&code.trim().toUpperCase()==='VITA2025'){let n=readStamps();if(n<10){writeStamps(n+1);alert('Stamp added!')}else{alert('You already have 10 stamps. Redeem your free drink!')}}else if(code!==null){alert('Invalid code.')}}
function redeemReward(){if(readStamps()>=10){alert('Show this screen to staff to redeem 1 FREE drink. Staff can reset your card.')}}
function resetStamps(){const code=prompt('Staff PIN to reset (hint: VITA2025):');if(code&&code.trim().toUpperCase()==='VITA2025'){writeStamps(0);alert('Loyalty card reset.')}else if(code!==null){alert('Invalid PIN.')}}
window.VitaBella={loadMenu,loadEvents,renderStamps,addStampWithCode,redeemReward,resetStamps};
